# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_mailbox', '0007_auto_20171123_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzed', models.BooleanField(default=False)),
                ('data', models.TextField(null=True)),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_mailbox.Message')),
            ],
        ),
    ]
