# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyzed',
            old_name='message_id',
            new_name='message',
        ),
    ]
